//
//  UserInfoRouter.swift
//  ApplicationChallenge
//
//  Created by Sakdinan Sukkhasem on 22/1/22.
//  Copyright (c) 2022 Sakdinan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UserInfoRoutingLogic {
    //    func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol UserInfoDataPassing {
    var dataStore: UserInfoDataStore? { get }
}

class UserInfoRouter: NSObject, UserInfoRoutingLogic, UserInfoDataPassing {
    weak var viewController: UserInfoViewController?
    var dataStore: UserInfoDataStore?
    
    // MARK: Routing
    
//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }
    
    // MARK: Navigation
    
//    func navigateToSomewhere(source: UserInfoViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
    
    // MARK: Passing data
    
//    func passDataToSomewhere(source: UserInfoDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
