//
//  UserInfoInteractor.swift
//  ApplicationChallenge
//
//  Created by Sakdinan Sukkhasem on 22/1/22.
//  Copyright (c) 2022 Sakdinan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol UserInfoBusinessLogic {
    func doSomething(request: UserInfo.Something.Request)
}

protocol UserInfoDataStore {
//    var name: String { get set }
}

class UserInfoInteractor: UserInfoBusinessLogic, UserInfoDataStore {
    var presenter: UserInfoPresentationLogic?
    var worker: UserInfoWorker?
//    var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: UserInfo.Something.Request) {
        worker = UserInfoWorker()
        worker?.doSomeWork()
        
        let response = UserInfo.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
