//
//  UserInfoPresenter.swift
//  ApplicationChallenge
//
//  Created by Sakdinan Sukkhasem on 22/1/22.
//  Copyright (c) 2022 Sakdinan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserInfoPresentationLogic {
    func presentLoading(response: UserInfo.Loading.Response)
}

class UserInfoPresenter: UserInfoPresentationLogic {
    weak var viewController: UserInfoDisplayLogic?
    
    func presentLoading(response: UserInfo.Loading.Response) {
        let viewModel = UserInfo.Loading.ViewModel(isShow: response.isShow)
        viewController?.displayLoading(viewModel: viewModel)
    }
}
