//
//  UserInfoWorker.swift
//  ApplicationChallenge
//
//  Created by Sakdinan Sukkhasem on 22/1/22.
//  Copyright (c) 2022 Sakdinan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum UserInfoWorkerResult {
    enum Users {
        case success([User])
        case error(String)
    }
}

class UserInfoWorker {
    lazy var userUsecase: UserUsecaseInterface = UserUsecase()
    
    func getUsers(completion: @escaping ((UserInfoWorkerResult.Users) -> Void)) {
        userUsecase.getUsers { result in
            switch result {
            case .success(let users):
                completion(.success(users))
            case .error(let message):
                completion(.error(message))
            }
        }
    }
}
